[project]
name = "linkbot-slack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "psycopg2-binary>=2.9.13",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
    "slack-bolt>=1.30.0",
    "sqlmodel>=0.0.47",
    "uvicorn>=0.54.0",
]
